version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: ./
      dockerfile: Dockerfile
    #      npx prisma migrate reset
    command: sh -c "npx prisma migrate deploy&& npx prisma db seed && npm run start:prod"
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "4g"
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - ./.env
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "2g"
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: nest-db